export enum Countries {
  SPAIN = 'España',
  GERMANY = 'Alemania',
  BELGIUM = 'Bélgica',
  DENMARK = 'Dinamarca',
  FINLAND = 'Finlandia',
  FRANCE = 'Francia',
  NETHERLANDS = 'Holanda',
  IRELAND = 'Irlanda',
  ITALY = 'Italia',
  NORWAY = 'Noruega',
  UNITED_KINGDOM = 'Reino Unido',
  SWEDEN = 'Suecia',
  SWITZERLAND = 'Suiza',
  OTHER_COUNTRIES = 'Otros países',
}
