export enum Concepts {
  ACCOMMODATION = 'ALOJAMIENTO',
  NATIONAL_INTERNATIONAL_TRANSPORT = 'TRANSPORTE NACIONAL / INTERNACIONAL',
  LOCAL_TRANSPORTATION = 'TRANSPORTE LOCAL',
  FEEDING = 'ALIMENTACIÓN',
  RECREATION_CULTURE_AND_SPORTS_ACTIVITIES = 'RECREACIÓN, CULTURA Y ACTIVIDADES DEPORTIVAS',
  SHOPPING = 'COMPRAS',
  OTHERS = 'OTROS',
}
