export enum ResidencePlaceResponse {
  GERMANY = 'DE',
  AUSTRIA = 'AT',
  BELGIUM = 'BE',
  CANADA = 'CA',
  DENMARK = 'DK',
  UNITED_STATES = 'US',
  FINLAND = 'FI',
  FRANCE = 'FR',
  BRITAIN = 'UK',
  NETHERLANDS = 'NL',
  IRELAND = 'IR',
  ITALY = 'IT',
  NORWAY = 'NO',
  SWEDEN = 'SE',
  SWITZERLAND = 'CH',
  SPAIN_RESIDENTS_EXCEPT_CANARY_ISLANDS = 'ES_XES70',
}
